namespace Model.Entities;

public enum EAggregationOperatorType
{
    CONDITIONAL_EXPRESSION_OPERATOR, OBJECT_EXPRESSION_OPERATOR, ACCUMULATOR, ARRAY_EXPRESSION_OPERATOR, COMPARISON_EXPREESSION_OPERATOR, BOOLEAN_EXPRESSION_OPERATOR, ARITHMETIC_EXPRESSION_OPERATOR
}